# Generated by Django 2.2.6 on 2019-10-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articalmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
