# Generated by Django 3.0 on 2019-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191222_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='content'),
        ),
    ]
