# Generated by Django 3.0.6 on 2020-05-23 15:53

import Billgen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=Billgen.models.get_default_count, unique=True)),
                ('item_name', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
            options={
                'ordering': ['sno'],
            },
        ),
    ]
