# Generated by Django 2.2.6 on 2019-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.TextField(default='This is a Fruit')),
                ('Price', models.TextField()),
                ('Summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
